Repository sapphiredev/shapeshift, pull requests merged in 2022-08, with the labels that each got.

#179 fix: typescript 4.8 compatibility
  package.json
  src/lib/Shapes.ts
  src/lib/util-types.ts
  yarn.lock
Labels: priority:high, semver:patch, typings

#183 feat: add `Validator#is`
  src/validators/BaseValidator.ts
  tests/validators/base.test.ts
Labels: feature, semver:minor

#174 build: enable rollup tree-shaking
  package.json
  tsup.config.ts
  yarn.lock
Labels: blocked, performance
