Repository sapphiredev/shapeshift, pull requests merged in 2022-03, with the labels that each got.

#51 refactor: add macros for tests
  src/constraints/DateConstraints.ts
  src/validators/ArrayValidator.ts
  src/validators/BaseValidator.ts
  src/validators/BigIntValidator.ts
  src/validators/BooleanValidator.ts
  src/validators/DateValidator.ts
  src/validators/DefaultValidator.ts
  src/validators/InstanceValidator.ts
  src/validators/LiteralValidator.ts
  src/validators/MapValidator.ts
  src/validators/NeverValidator.ts
  src/validators/NullishValidator.ts
  src/validators/NumberValidator.ts
  src/validators/ObjectValidator.ts
  src/validators/RecordValidator.ts
  src/validators/SetValidator.ts
  src/validators/StringValidator.ts
  tests/common/macros/comparators.ts
  tests/validators/array.test.ts
  tests/validators/base.test.ts
  tests/validators/bigint.test.ts
  tests/validators/boolean.test.ts
  tests/validators/date.test.ts
  tests/validators/enum.test.ts
  tests/validators/instance.test.ts
  tests/validators/literal.test.ts
  tests/validators/map.test.ts
  tests/validators/never.test.ts
  tests/validators/null.test.ts
  tests/validators/nullish.test.ts
  tests/validators/number.test.ts
  tests/validators/object.test.ts
  tests/validators/record.test.ts
  tests/validators/set.test.ts
  tests/validators/string.test.ts
  tests/validators/undefined.test.ts
  tests/validators/union.test.ts
Labels: Meta: Refactor

#52 feat(Array): generate tuple types with given length
  README.md
  src/lib/Shapes.ts
  src/type-exports.ts
  src/validators/ArrayValidator.ts
  tests/validators/array.test.ts
Labels: Meta: Feature, Meta: Typings

#55 feat: allow the use of module: NodeNext
  package.json
Labels: SEM: N/A

#54 feat: add NativeEnum validator
  src/index.ts
  src/lib/Shapes.ts
  src/lib/errors/UnknownEnumValueError.ts
  src/type-exports.ts
  src/validators/BaseValidator.ts
  src/validators/DefaultValidator.ts
  src/validators/NativeEnumValidator.ts
  tests/lib/errors/UnknownEnumValueError.test.ts
  tests/validators/nativeEnum.test.ts
Labels: Meta: Feature, SEM: Minor

#61 perf(s.string): speed up URL and IP constraints
  src/constraints/ArrayLengthConstraints.ts
  src/constraints/BigIntConstraints.ts
  src/constraints/BooleanConstraints.ts
  src/constraints/DateConstraints.ts
  src/constraints/NumberConstraints.ts
  src/constraints/StringConstraints.ts
  src/constraints/base/IConstraint.ts
  src/constraints/util/common/combinedResultFn.ts
  src/constraints/util/urlValidators.ts
  src/index.ts
  src/lib/errors/BaseConstraintError.ts
  src/lib/errors/ExpectedConstraintError.ts
  src/lib/errors/MultiplePossibilitiesConstraintError.ts
  src/type-exports.ts
  tests/common/macros/comparators.ts
  tests/lib/errors/ExpectedConstraintError.test.ts
  tests/lib/errors/MultiplePossibilitiesConstraintError.test.ts
  tests/validators/array.test.ts
  tests/validators/bigint.test.ts
  tests/validators/boolean.test.ts
  tests/validators/date.test.ts
  tests/validators/number.test.ts
  tests/validators/string.test.ts
Labels: SEM: Patch, Type: Performance

#63 refactor(email-validator): rewrite for huge performance boosts
  src/constraints/util/emailValidator.ts
Labels: Meta: Refactor, SEM: Patch, Type: Performance

#62 fix(s.union): fix union overrides
  src/validators/UnionValidator.ts
  tests/validators/union.test.ts
Labels: Meta: BugFix, Priority: High, SEM: Patch

#66 feat(s.object): add passthrough
  README.md
  src/validators/ObjectValidator.ts
  tests/validators/object.test.ts
Labels: Meta: Feature, SEM: Minor

#67 tests: increase coverage
  src/constraints/DateConstraints.ts
  src/validators/DateValidator.ts
  tests/validators/base.test.ts
  tests/validators/date.test.ts
  tests/validators/union.test.ts
Labels: Meta: Feature, SEM: Minor

#68 test: even more test coverage
  jest.config.mjs
  package.json
  tsconfig.eslint.json
  yarn.lock
Labels: Meta: Refactor

#70 test: increase test coverage for email validation
  .vscode/settings.json
  jest.config.mjs
  tests/common/macros/comparators.ts
  tests/jest.setup.ts
  tests/validators/string.test.ts
Labels: Meta: Error Handling

#72 tests: add coverage for `combinedErrorFn`
  tests/util/common/combinedResultFn.test.ts
Labels: SEM: Patch

#75 docs(readme): add todo notice for `reshape` and `function` validations
  README.md
Labels: Meta: Documentation

#79 chore: optimize NativeEnum
  src/validators/NativeEnumValidator.ts
Labels: SEM: Patch, Type: Enhancement
