Repository sapphiredev/shapeshift, pull requests merged in 2022-05, with the labels that each got.

#99 fix(ObjectValidator): don't run validation on arrays
  src/validators/ObjectValidator.ts
  tests/validators/object.test.ts
Labels: SEM: Patch

#100 fix: expand method names
  README.md
  src/constraints/ArrayLengthConstraints.ts
  src/constraints/BigIntConstraints.ts
  src/constraints/DateConstraints.ts
  src/constraints/NumberConstraints.ts
  src/constraints/StringConstraints.ts
  src/constraints/TypedArrayLengthConstraints.ts
  src/constraints/type-exports.ts
  src/constraints/util/operators.ts
  src/lib/Shapes.ts
  src/type-exports.ts
  src/validators/ArrayValidator.ts
  src/validators/BigIntValidator.ts
  src/validators/BooleanValidator.ts
  src/validators/DateValidator.ts
  src/validators/NumberValidator.ts
  src/validators/StringValidator.ts
  src/validators/TypedArrayValidator.ts
  tests/validators/array.test.ts
  tests/validators/base.test.ts
  tests/validators/bigint.test.ts
  tests/validators/boolean.test.ts
  tests/validators/date.test.ts
  tests/validators/literal.test.ts
  tests/validators/number.test.ts
  tests/validators/string.test.ts
  tests/validators/typedArray.test.ts
Labels: SEM: Major

#101 perf: speed up object validation a LOT
  src/validators/ObjectValidator.ts
  tests/validators/object.test.ts
Labels: SEM: Major, Type: Performance

#102 feat: add 2 utility types inspired by yup and co
  src/index.ts
  src/utility-types.ts
Labels: Meta: Feature, Priority: High, SEM: Minor

#108 docs(readme): clarify the difference between validations and schemas and add table of contents
  README.md
Labels: Meta: Documentation
