Repository sapphiredev/shapeshift, pull requests merged in 2022-06, with the labels that each got.

#122 fix(ObjectValidator): fix #121
  src/validators/ObjectValidator.ts
  tests/validators/object.test.ts
Labels: Meta: BugFix, Priority: High, SEM: Patch

#125 feat: add disabling of validators
  README.md
  src/index.ts
  src/lib/configs.ts
  src/validators/ArrayValidator.ts
  src/validators/BaseValidator.ts
  src/validators/MapValidator.ts
  src/validators/ObjectValidator.ts
  src/validators/RecordValidator.ts
  src/validators/SetValidator.ts
  src/validators/TupleValidator.ts
  tests/lib/configs.test.ts
Labels: Meta: Feature, SEM: Minor, Type: Enhancement

#128 fix: compile for es2020 instead of es2021
  .github/workflows/continuous-integration.yml
  README.md
  package.json
  src/lib/errors/CombinedError.ts
  src/lib/errors/CombinedPropertyError.ts
  src/lib/errors/ExpectedConstraintError.ts
  src/lib/errors/ExpectedValidationError.ts
  src/lib/errors/MultiplePossibilitiesConstraintError.ts
  src/lib/errors/UnknownPropertyError.ts
  src/lib/errors/ValidationError.ts
  tsconfig.base.json
  tsup.config.ts
Labels: SEM: Patch

#126 test: migrate to vitest
  .github/CODEOWNERS
  .github/husky/commit-msg
  .github/husky/pre-commit
  .github/workflows/continuous-integration.yml
  jest.config.mjs
  package.json
  tests/common/macros/comparators.ts
  tests/jest.setup.ts
  tests/tsconfig.json
  tests/util/common/combinedResultFn.test.ts
  tests/validators/array.test.ts
  tests/validators/base.test.ts
  tests/validators/date.test.ts
  tests/validators/enum.test.ts
  tests/validators/nativeEnum.test.ts
  tests/validators/never.test.ts
  tests/validators/null.test.ts
  tests/validators/nullish.test.ts
  tests/validators/passthrough.test.ts
  tests/validators/set.test.ts
  tests/validators/string.test.ts
  tests/validators/tuple.test.ts
  tests/validators/typedArray.test.ts
  tests/validators/undefined.test.ts
  tests/validators/union.test.ts
  tsconfig.eslint.json
  vitest.config.ts
  yarn.lock
Labels: Meta: Refactor, SEM: N/A

#133 fix: add generic type to parse
  src/validators/BaseValidator.ts
Labels: Meta: Refactor, Meta: Typings, SEM: Patch
