Repository sapphiredev/shapeshift, pull requests merged in 2022-07, with the labels that each got.

#149 refactor: port net module
  src/constraints/StringConstraints.ts
  src/constraints/util/net.ts
Labels: Meta: Refactor, Priority: Medium, SEM: Patch

#141 feat(arrays): add unique
  .all-contributorsrc
  .github/workflows/continuous-integration.yml
  README.md
  package.json
  scripts/no-bundle-test.mjs
  src/constraints/ArrayConstraints.ts
  src/constraints/type-exports.ts
  src/constraints/util/isUnique.ts
  src/validators/ArrayValidator.ts
  tests/lib/configs.test.ts
  tests/validators/array.test.ts
  tests/validators/date.test.ts
  tsup.config.ts
  yarn.lock
Labels: Meta: Dependencies, Meta: Documentation, Meta: Feature, Meta: Refactor, Priority: Medium, SEM: Minor

#148 feat: reshape finally
  README.md
  src/lib/util-types.ts
  src/validators/BaseValidator.ts
  tests/common/macros/comparators.ts
  tests/validators/base.test.ts
Labels: Meta: Feature, Priority: Medium, SEM: Minor, Status: WIP

#147 feat: lazy validator
  src/lib/Shapes.ts
  src/validators/LazyValidator.ts
  tests/validators/lazy.test.ts
Labels: Meta: Feature, Priority: Medium, SEM: Minor

#153 fix: fixed `s.array` type inference
  src/lib/Shapes.ts
Labels: Meta: BugFix, SEM: Patch
